---  # all ansible playbook should start with "---"
- hosts: loadbalancer
  become: true # asking Ansible to be Root user
  tasks:
    - name: install nginx
      # module apt is equivalent to apt-get
      apt: name=nginx state=present update_cache=yes

      # enabled represent start at system start up
      # state represent running state of the service
    - name: ensure nginx started
      service: name=nginx state=started enabled=yes
